=== DanGrew/homeschooling-app/content/schemas/dictionary/colouring.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Dictionary Colouring",
  "type": "object",
  "required": [
    "concept",
    "type",
    "viewBox",
    "shapes"
  ],
  "additionalProperties": false,
  "properties": {
    "concept": {
      "type": "string"
    },
    "type": {
      "type": "string",
      "const": "colouring"
    },
    "viewBox": {
      "type": "string",
      "pattern": "^[\\d.]+ [\\d.]+ [\\d.]+ [\\d.]+$"
    },
    "shapes": {
      "type": "array",
      "minItems": 1,
      "items": {
        "type": "object",
        "required": [
          "id",
          "tag",
          "attrs"
        ],
        "additionalProperties": false,
        "properties": {
          "id": {
            "type": "string"
          },
          "tag": {
            "type": "string",
            "enum": [
              "path",
              "ellipse",
              "circle",
              "rect",
              "polygon",
              "polyline",
              "line"
            ]
          },
          "attrs": {
            "type": "object",
            "additionalProperties": {
              "type": "string"
            }
          },
          "colour": {
            "type": [
              "string",
              "null"
            ],
            "pattern": "^#[0-9A-Fa-f]{6}$"
          },
          "noColour": {
            "type": "boolean"
          },
          "fixed": {
            "type": "boolean"
          }
        }
      }
    }
  }
}

=== DanGrew/homeschooling-app/content/dictionary/entries/orange/colouring.json
{
  "concept": "orange",
  "type": "colouring",
  "viewBox": "0 0 658.609376 549",
  "shapes": [
    {
      "id": "shape_1",
      "tag": "path",
      "attrs": {
        "d": "M 183.726563 167.140625 C 0 285.910156 84.648438 549 313.089844 535.808594 C 356.148438 533.320312 399.519532 513.75 433.1875 485.46875 C 658.609376 296.160156 420.507813 0 183.726563 167.140625",
        "stroke-width": "2"
      },
      "colour": "#FF8827"
    },
    {
      "id": "shape_2",
      "tag": "path",
      "attrs": {
        "d": "M 212.738282 200.769531 C 212.546876 201.046875 205.636719 193.878906 205 193.308594 C 199.476563 188.308594 193.6875 183.546875 188 178.707031 C 180.160157 172.027344 172.796876 165.597656 163.457032 160.539062 C 159.578126 158.429688 151.320313 156.828125 149.578126 152.6875 C 147.007813 146.578125 151.777344 136.347656 154.386719 130.828125 C 156.257813 126.898438 158.707032 120.9375 163.070313 118.609375 C 170.867188 114.449219 181.160157 128.308594 184.667969 132.367188 C 188.347657 136.628906 192.058594 140.847656 195.910157 144.980469 C 205.75 155.539062 246.417969 179.679688 212.738282 200.769531",
        "stroke-width": "2"
      },
      "colour": "#668E1B"
    },
    {
      "id": "shape_3",
      "tag": "path",
      "attrs": {
        "d": "M 157.199219 148.179688 C 152.007813 146.039062 160.488282 123.917969 169.136719 123.769531 C 175.796876 123.640625 166.96875 152.207031 157.199219 148.179688",
        "stroke-width": "2",
        "fill": "#BECB83"
      },
      "noColour": true,
      "fixed": true
    },
    {
      "id": "shape_4",
      "tag": "path",
      "attrs": {
        "d": "M 215.5 189.378906 C 215.257813 189.398438 215.488282 176.019531 217.957032 166.21875 C 223.839844 142.910156 233.859376 120.390625 246.628907 100.597656 C 284.976563 41.140625 356.367188 25.507812 417.847657 48.769531 C 433.179688 54.570312 447.238282 62.339844 459.757813 73.628906 C 461.9375 75.589844 470.046876 80.808594 470.660157 84.089844 C 470.757813 84.648438 468.589844 83.949219 468.578126 83.949219 C 465.519532 83.160156 462.429688 82.539062 459.328126 81.9375 C 452.410157 80.609375 445.429688 79.488281 438.417969 78.839844 C 416.617188 76.808594 393.820313 79.589844 372.378907 83.847656 C 311.257813 96 255.207032 134.707031 220.417969 190.25",
        "stroke-width": "2"
      },
      "colour": "#BECB83"
    },
    {
      "id": "shape_5",
      "tag": "path",
      "attrs": {
        "d": "M 213.179688 200.777344 C 217.976563 185.320312 232.929688 169.867188 242.949219 158.539062 C 276.636719 120.449219 318.777344 92.878906 367 82.75 C 393.386719 77.207031 420.9375 74.289062 447.71875 78.1875 C 450.558594 78.597656 468.660157 79.9375 469.648438 84.238281 C 469.828126 85 455.367188 90.179688 454.347657 90.617188 C 435.648438 98.609375 417.886719 109.769531 399.367188 118.359375 C 382.570313 126.160156 365.519532 132.648438 347.929688 138.027344 C 310.289063 149.558594 245.808594 175.570312 213.179688 200.777344",
        "stroke-width": "2"
      },
      "colour": "#668E1B"
    },
    {
      "id": "shape_6",
      "tag": "path",
      "attrs": {
        "d": "M 122.109376 360.027344 C 110.9375 343.589844 117.109376 297.75 119.929688 290.179688 C 130 263.140625 146.648438 227.238281 180.429688 225.328125 C 193.019532 224.617188 206.289063 225.480469 218.007813 220.097656 C 247.558594 206.539062 272.878907 168.71875 301.878907 206.71875 C 376.078126 303.949219 175.519532 438.640625 122.109376 360.027344",
        "stroke-width": "2"
      },
      "colour": "#FFD889"
    },
    {
      "id": "shape_7",
      "tag": "path",
      "attrs": {
        "d": "M 241.257813 487.929688 C 248.488282 491.71875 316.738282 474.578125 324.257813 471.867188 C 403.898438 443.230469 436.296876 385.738281 441.726563 302.558594 C 442.988282 283.21875 438.257813 263.238281 440.917969 244.117188 C 443.410157 226.148438 457.160157 225.738281 469.726563 235.910156 C 503.097657 262.9375 503.207032 319.25 492.21875 356.539062 C 468.570313 436.777344 412.097657 502.539062 331.660157 515.179688 C 316.617188 517.539062 258.9375 511.628906 241.257813 487.929688",
        "stroke-width": "2"
      },
      "colour": "#CB5C0D"
    }
  ]
}

=== DanGrew/homeschooling-app/content/dictionary/entries/first-aid/colouring.json
{
  "concept": "first-aid",
  "type": "colouring",
  "viewBox": "0 0 372.3 354.8",
  "shapes": [
    {
      "id": "shape_11",
      "tag": "path",
      "attrs": {
        "d": "M 290.8 27.6 v 88.2 h -43.7 v -72.8 h -131 v 72.8 h -43.7 V 27.6 c 0 -15.2 12.3 -27.6 27.6 -27.6 h 163.2 C 278.5 0 290.8 12.3 290.8 27.6 z",
        "stroke-width": "2"
      },
      "colour": "#FFFFFF"
    },
    {
      "id": "shape_12",
      "tag": "path",
      "attrs": {
        "d": "M 38 342.8 c -18.8 0 -34 -15.3 -34 -34 v -198 c 0 -18.8 15.3 -34 34 -34 h 287.3 c 18.8 0 34 15.3 34 34 v 198 c 0 18.8 -15.3 34 -34 34 H 38 z",
        "stroke-width": "2"
      },
      "colour": "#FFFFFF"
    },
    {
      "id": "shape_13",
      "tag": "path",
      "attrs": {
        "d": "M 325.3 80.8 c 16.6 0 30 13.4 30 30 v 198 c 0 16.6 -13.4 30 -30 30 H 38 c -16.6 0 -30 -13.4 -30 -30 v -198 c 0 -16.6 13.4 -30 30 -30 H 325.3 M 325.3 72.8 H 38 c -21 0 -38 17.1 -38 38 v 198 c 0 21 17.1 38 38 38 h 287.3 c 21 0 38 -17.1 38 -38 v -198 C 363.3 89.8 346.3 72.8 325.3 72.8 L 325.3 72.8 z",
        "stroke-width": "2"
      },
      "colour": "#6D0F05"
    },
    {
      "id": "shape_14",
      "tag": "line",
      "attrs": {
        "x1": "8.000000000000007",
        "y1": "229.60000000000002",
        "x2": "355.29999999999995",
        "y2": "229.60000000000002",
        "stroke-width": "2"
      },
      "noColour": true,
      "colour": null
    },
    {
      "id": "shape_15",
      "tag": "rect",
      "attrs": {
        "x": "72.5",
        "y": "198.80000000000007",
        "width": "24.3",
        "height": "61.7",
        "stroke-width": "2"
      },
      "colour": "#FF1E46"
    },
    {
      "id": "shape_16",
      "tag": "rect",
      "attrs": {
        "x": "270.29999999999995",
        "y": "198.80000000000007",
        "width": "24.3",
        "height": "61.7",
        "stroke-width": "2"
      },
      "colour": "#FF1E46"
    },
    {
      "id": "shape_17",
      "tag": "rect",
      "attrs": {
        "x": "160.70000000000002",
        "y": "106.80000000000007",
        "width": "41.9",
        "height": "100.3",
        "stroke-width": "2"
      },
      "colour": "#FF1E46"
    },
    {
      "id": "shape_18",
      "tag": "rect",
      "attrs": {
        "x": "131.5",
        "y": "136",
        "width": "100.3",
        "height": "41.9",
        "stroke-width": "2"
      },
      "colour": "#FF1E46"
    },
    {
      "id": "shape_19",
      "tag": "path",
      "attrs": {
        "d": "M 341.7 98.6 c 0 -1.2 -0.5 -2.4 -1.3 -3.2 c -0.8 -0.8 -2.1 -1.4 -3.2 -1.3 c -1.2 0.1 -2.4 0.4 -3.2 1.3 c -0.8 0.9 -1.4 2 -1.3 3.2 c 0 1 0.3 1.9 0.9 2.7 c 0 0.1 0.1 0.2 0.1 0.3 c 0.4 0.6 0.8 1.1 1.5 1.5 c 0.6 0.4 1.3 0.6 2.1 0.6 c 0.7 0 1.4 -0.2 2.1 -0.6 c 0.6 -0.4 1.1 -0.8 1.5 -1.5 c 0 0 0 -0.1 0.1 -0.1 C 341.3 100.7 341.7 99.5 341.7 98.6 z",
        "stroke-width": "2"
      },
      "colour": "#6D0F05"
    },
    {
      "id": "shape_20",
      "tag": "path",
      "attrs": {
        "d": "M 24.4 98.1 c -6.1 0 -6.1 9.5 0 9.5 C 30.5 107.6 30.5 98.1 24.4 98.1 z",
        "stroke-width": "2"
      },
      "colour": "#6D0F05"
    }
  ]
}

=== DanGrew/homeschooling-app/content/dictionary/entries/banana/colouring.json
{
  "concept": "banana",
  "type": "colouring",
  "viewBox": "0 0 490.257812 545.6875",
  "shapes": [
    {
      "id": "shape_1",
      "tag": "path",
      "attrs": {
        "d": "M 130.867187 256.449219 C 128.21875 254.839844 125.890625 242.648438 125.609375 240.078126 C 123.738281 223.417969 123.039062 206.617188 121.457031 189.917969 C 120.277344 177.488282 119.410156 165.027344 118.558594 152.570313 C 115.800781 112.070313 113.648437 2.289063 175.910156 0.839844 C 212.347656 0 218.367187 35.417969 215.820312 63.617188 C 213.238281 92.199219 218.980468 119.71875 226.488281 146.558594 C 228.558594 153.988282 235.550781 173.457032 237.117187 179.726563 C 240.75 194.308594 246.257812 205.078126 244.21875 220.167969 C 242.75 231.078126 230.25 242.25 225.71875 252.289063 C 222.527344 259.347657 223.289062 270.117188 219.539062 276.296876 C 218.777344 277.539063 216.507812 276.007813 215.71875 275.519532 C 204.6875 268.609376 197 256.789063 185.929687 249.320313 C 168.917968 237.820313 148.160156 249.886719 130.867187 256.449219",
        "stroke-width": "2"
      },
      "colour": "#F3DFC4"
    },
    {
      "id": "shape_2",
      "tag": "path",
      "attrs": {
        "d": "M 179.9375 242.898438 C 180.308594 242.738282 170.328125 219.738282 169.457031 217.808594 C 161.320312 199.867188 157.160156 184.957032 152.398437 168.089844 C 140.660156 126.519532 145.449218 86.078126 158.488281 45.75 C 162.609375 33 170.800781 11.589844 186.71875 11.25 C 206.6875 10.839844 202.820312 49.859376 202.539062 62.058594 C 202.140625 79.457032 201.839844 88.886719 202.789062 106.277344 C 203.378906 117.007813 209.679687 150.707032 213.449218 160.777344 C 220.558594 179.726563 233.25 201.398438 228.847656 205.796876 C 225.300781 209.347657 217.929687 221.957032 215.527344 227.757813 C 213.828125 231.847657 211.109375 248.789063 205.96875 249.679688 C 200.089844 250.707032 185.4375 244.867188 179.9375 242.898438",
        "stroke-width": "2"
      },
      "colour": "#F9EBD7"
    },
    {
      "id": "shape_3",
      "tag": "path",
      "attrs": {
        "d": "M 211.007812 261.199219 C 212.097656 224.046876 245.140625 194.269532 282.378906 199.226563 C 286.039062 199.71875 289.730468 204.199219 293.300781 205.609376 C 324.820312 218.007813 356.097656 229.757813 380.640625 254.257813 C 394 267.597657 404.820312 283.386719 416.410156 298.207032 C 426.949218 311.6875 453.539062 305.519532 466.800781 315.976563 C 469.390625 318.019532 458.578125 330.148438 456.488281 334.589844 C 454.128906 339.617188 442.828125 339.367188 435 334.589844 C 421.96875 326.636719 406.867187 309.929688 393.539062 295.839844 C 366.390625 267.148438 349.75 237.449219 310.597656 225.21875 C 292.410156 219.527344 268.359375 221.578126 269.25 245.277344 C 271.199218 297.417969 335.9375 360.429688 380.667968 380.546876 C 404.707031 391.359376 430.289062 389.667969 454.757812 397.589844 C 460.480468 399.4375 469.667968 410.628907 465.9375 417.117188 C 462.988281 422.238282 449.808594 422.597657 444.917968 422.9375 C 423.140625 424.449219 396.699218 428.136719 375.769531 423.199219 C 305.5 406.628907 258.46875 370.476563 219.800781 308.628907 C 210.167968 293.226563 192.320312 281.398438 179.378906 268.589844 C 175.859375 265.109376 167.707031 254.6875 168.230468 250.328126 C 170.46875 231.859376 207.628906 261.527344 211.007812 261.199219",
        "stroke-width": "2"
      },
      "colour": "#FEDE4E"
    },
    {
      "id": "shape_4",
      "tag": "path",
      "attrs": {
        "d": "M 164.050781 249.527344 C 163.640625 249.628907 164.117187 249.796876 164.300781 249.867188 C 167.769531 251.339844 170.957031 254.597657 173.769531 257.007813 C 180.308594 262.617188 186.339844 268.917969 192.5 274.9375 C 210.5 292.539063 225.519531 312.007813 240.488281 332.160157 C 276.457031 380.527344 328.367187 412.578126 388.640625 420.578126 C 397.328125 421.726563 406.007812 422.457032 414.757812 423 C 420.019531 423.320313 425.21875 423.257813 430.457031 422.667969 C 450.980468 420.359376 467.570312 406.867188 478.679687 426.738282 C 481.839844 432.386719 482.199218 436.617188 478.789062 442.398438 C 454.769531 483.238282 391.199218 491.386719 349.019531 487.1875 C 280.347656 480.339844 228.6875 453.410157 183.539062 401.007813 C 174.300781 390.277344 159.230468 379.386719 154.230468 365.910157 C 147.570312 347.957032 150.570312 336.46875 151.71875 317.820313 C 152.808594 299.976563 154.867187 265.167969 164.050781 249.527344",
        "stroke-width": "2"
      },
      "colour": "#EFC90E"
    },
    {
      "id": "shape_5",
      "tag": "path",
      "attrs": {
        "d": "M 473.488281 422.070313 C 467.46875 420.839844 450.597656 405.46875 458.609375 399.949219 C 479.207031 385.75 490.257812 436.660157 471.820312 419.6875",
        "stroke-width": "2",
        "fill": "#795548"
      },
      "colour": "#93722B"
    },
    {
      "id": "shape_6",
      "tag": "path",
      "attrs": {
        "d": "M 179.378906 245.019532 C 162.5 250.667969 156.589844 286.976563 153.820312 301.25 C 142.769531 358.070313 165.640625 415.976563 160.5 473.269532 C 158.9375 490.699219 152.398437 545.6875 125.820312 541.207032 C 98.9375 536.667969 77.207031 496.046876 65.070312 475.296876 C 42.988281 437.558594 0 349.1875 28.71875 306.539063 C 51.507812 272.679688 105.398437 262.136719 141.648437 249.796876 C 145.410156 248.519532 177.558594 237.757813 179.378906 245.019532",
        "stroke-width": "2"
      },
      "colour": "#F3DFC4"
    },
    {
      "id": "shape_7",
      "tag": "path",
      "attrs": {
        "d": "M 244.550781 206.808594 C 243.589844 206.578126 251.519531 199.167969 251.988281 198.777344 C 256.777344 194.867188 261.757812 191.277344 266.878906 187.796876 C 284.9375 175.488282 305.457031 168.75 327.160156 174.976563 C 376.917968 189.269532 421.980468 229.699219 448.988281 272.578126 C 456.558594 284.597657 472.859375 314.609376 464.457031 329.296876 C 458.75 339.269532 447.457031 332.9375 440.308594 328.320313 C 419.808594 315.078126 404.117187 295.367188 387.550781 277.796876 C 335.367187 222.457032 316.140625 206.808594 244.550781 206.808594",
        "stroke-width": "2"
      },
      "colour": "#F3DFC4"
    }
  ]
}

=== DanGrew/homeschooling-app/content/dictionary/entries/train/colouring.json
{
  "concept": "train",
  "type": "colouring",
  "viewBox": "0 0 806.2 273.3",
  "shapes": [
    {
      "id": "shape_1",
      "tag": "rect",
      "attrs": {
        "x": "106.6",
        "y": "224",
        "width": "413",
        "height": "10",
        "stroke-width": "2"
      },
      "colour": "#E74C3C"
    },
    {
      "id": "shape_2",
      "tag": "rect",
      "attrs": {
        "x": "661.6",
        "y": "93",
        "width": "14",
        "height": "72",
        "stroke-width": "2"
      },
      "colour": "#E74C3C"
    },
    {
      "id": "shape_3",
      "tag": "rect",
      "attrs": {
        "x": "698.6",
        "y": "67",
        "width": "32",
        "height": "103",
        "stroke-width": "2"
      },
      "colour": "#E74C3C"
    },
    {
      "id": "shape_4",
      "tag": "polygon",
      "attrs": {
        "points": "700.4 99 729.1 99 738.7 62.2 690.8 62.7",
        "stroke-width": "2"
      },
      "colour": "#F39C12"
    },
    {
      "id": "shape_5",
      "tag": "path",
      "attrs": {
        "d": "M 683.6 89.8 c 0 -6 -4.8 -10.8 -10.8 -10.8 h -1.5 c -6 0 -10.8 4.8 -10.8 10.8 v 7.5 c 0 6 4.8 10.8 10.8 10.8 h 1.5 c 6 0 10.8 -4.8 10.8 -10.8 V 89.8 z",
        "stroke-width": "2"
      },
      "colour": "#F39C12"
    },
    {
      "id": "shape_6",
      "tag": "path",
      "attrs": {
        "d": "M 501.6 237.4 c 0 6.2 4.5 11.6 10.7 11.6 h 284.5 c 6.2 0 9.4 -4.9 7.2 -10.6 l -38.5 -100.5 c -2.2 -5.7 -9.1 -10.9 -15.2 -10.9 H 512.3 c -6.2 0 -10.7 5.7 -10.7 11.9 V 237.4 z",
        "stroke-width": "2"
      },
      "colour": "#1ABC9C"
    },
    {
      "id": "shape_7",
      "tag": "rect",
      "attrs": {
        "x": "501.6",
        "y": "24.000000000000004",
        "width": "132",
        "height": "167",
        "stroke-width": "2"
      },
      "colour": "#1ABC9C"
    },
    {
      "id": "shape_8",
      "tag": "rect",
      "attrs": {
        "x": "519.6",
        "y": "123",
        "width": "98",
        "height": "112",
        "stroke-width": "2"
      },
      "colour": "#27AE60"
    },
    {
      "id": "shape_9",
      "tag": "path",
      "attrs": {
        "d": "M 486.6 21.4 C 486.6 33 497.7 42 510.5 42 h 117.5 c 12.8 0 23.6 -9 23.6 -20.6 v -0.1 c 0 -11.5 -10.7 -21.3 -23.6 -21.3 H 510.5 c -12.8 0 -23.9 9.8 -23.9 21.3 V 21.4 z",
        "stroke-width": "2"
      },
      "colour": "#E74C3C"
    },
    {
      "id": "shape_10",
      "tag": "circle",
      "attrs": {
        "cx": "734.8000000000001",
        "cy": "244.3",
        "r": "26.6",
        "stroke-width": "2"
      },
      "colour": "#1F3A93"
    },
    {
      "id": "shape_11",
      "tag": "circle",
      "attrs": {
        "cx": "654.6",
        "cy": "244.3",
        "r": "26.6",
        "stroke-width": "2"
      },
      "colour": "#1F3A93"
    },
    {
      "id": "shape_12",
      "tag": "circle",
      "attrs": {
        "cx": "561.2",
        "cy": "229.5",
        "r": "41.5",
        "stroke-width": "2"
      },
      "colour": "#1F3A93"
    },
    {
      "id": "shape_13",
      "tag": "path",
      "attrs": {
        "d": "M 658.6 246.2 c 0 -1.2 -1 -2.2 -2.2 -2.2 h -95.5 c -1.2 0 -2.2 1 -2.2 2.2 v 4.5 c 0 1.2 1 2.2 2.2 2.2 h 95.5 c 1.2 0 2.2 -1 2.2 -2.2 V 246.2 z",
        "stroke-width": "2"
      },
      "colour": "#BDC3C7"
    },
    {
      "id": "shape_14",
      "tag": "rect",
      "attrs": {
        "x": "519.6",
        "y": "58",
        "width": "98",
        "height": "65",
        "stroke-width": "2"
      },
      "colour": "#FFFFFF"
    },
    {
      "id": "shape_15",
      "tag": "polygon",
      "attrs": {
        "points": "247.8 152 457.3 152 451.5 179 253.7 179",
        "stroke-width": "2"
      },
      "colour": "#F39C12"
    },
    {
      "id": "shape_16",
      "tag": "polygon",
      "attrs": {
        "points": "451.5 179 435.8 249 269.4 249 253.7 179",
        "stroke-width": "2"
      },
      "colour": "#F1C40F"
    },
    {
      "id": "shape_17",
      "tag": "path",
      "attrs": {
        "d": "M 368.1 244.3 c 0 14.7 11.9 26.6 26.6 26.6 c 14.7 0 26.6 -11.9 26.6 -26.6 c 0 -14.7 -11.9 -26.6 -26.6 -26.6 C 380.1 217.7 368.1 229.6 368.1 244.3 z",
        "stroke-width": "2"
      },
      "colour": "#1F3A93"
    },
    {
      "id": "shape_18",
      "tag": "circle",
      "attrs": {
        "cx": "312.20000000000005",
        "cy": "244.3",
        "r": "26.6",
        "stroke-width": "2"
      },
      "colour": "#1F3A93"
    },
    {
      "id": "shape_19",
      "tag": "polygon",
      "attrs": {
        "points": "0 155 209.5 155 203.7 182 5.9 182",
        "stroke-width": "2"
      },
      "colour": "#F39C12"
    },
    {
      "id": "shape_20",
      "tag": "polygon",
      "attrs": {
        "points": "203.7 182 188 250 21.6 250 5.9 182",
        "stroke-width": "2"
      },
      "colour": "#F1C40F"
    },
    {
      "id": "shape_21",
      "tag": "circle",
      "attrs": {
        "cx": "147",
        "cy": "246.7",
        "r": "26.6",
        "stroke-width": "2"
      },
      "colour": "#1F3A93"
    },
    {
      "id": "shape_22",
      "tag": "circle",
      "attrs": {
        "cx": "64.4",
        "cy": "246.7",
        "r": "26.6",
        "stroke-width": "2"
      },
      "colour": "#1F3A93"
    },
    {
      "id": "shape_23",
      "tag": "path",
      "attrs": {
        "d": "M 770.9 152.3 c 0 0 -23.4 26 21.4 55.6",
        "stroke-width": "2"
      },
      "colour": "#F1C40F"
    }
  ]
}

=== DanGrew/homeschooling-app/content/dictionary/entries/stethoscope/colouring.json
{
  "concept": "stethoscope",
  "type": "colouring",
  "viewBox": "0 0 340.4 361.4",
  "shapes": [
    {
      "id": "shape_10",
      "tag": "path",
      "attrs": {
        "d": "M 78.4 19.5 H 41.7 c 0 0 -41.7 171.9 87.2 178.2",
        "stroke-width": "2"
      },
      "noColour": true,
      "colour": null
    },
    {
      "id": "shape_11",
      "tag": "path",
      "attrs": {
        "d": "M 190.9 19.5 h 36.7 c 0 0 41.7 171.9 -87.2 178.2",
        "stroke-width": "2"
      },
      "noColour": true,
      "colour": null
    },
    {
      "id": "shape_12",
      "tag": "ellipse",
      "attrs": {
        "cx": "85.20000000000005",
        "cy": "19.5",
        "rx": "9.3",
        "ry": "19.5",
        "stroke-width": "2"
      },
      "colour": "#9B8579"
    },
    {
      "id": "shape_13",
      "tag": "ellipse",
      "attrs": {
        "cx": "187.10000000000014",
        "cy": "19.5",
        "rx": "9.3",
        "ry": "19.5",
        "stroke-width": "2"
      },
      "colour": "#9B8579"
    },
    {
      "id": "shape_14",
      "tag": "path",
      "attrs": {
        "d": "M 141.2 193.4 c -8.8 34 -11 69.7 -6.2 104.4 c 2 14.4 5.4 29.3 15.1 40.2 c 8.9 10 22.9 15.4 36.2 14 c 13.4 -1.4 25.9 -9.6 32.5 -21.2 c 6.8 -11.9 7.5 -26.5 5.7 -40.1 c -1.7 -13.6 -5.7 -26.9 -7.5 -40.5 c -1.8 -13.6 -1.2 -28.1 5.4 -40.1 s 20.7 -20.6 34.2 -17.6 c 12.2 2.7 21 14.3 24.1 26.4 c 3.1 12.1 1.6 24.9 0.1 37.4",
        "stroke-width": "2"
      },
      "noColour": true,
      "colour": null
    },
    {
      "id": "shape_15",
      "tag": "path",
      "attrs": {
        "d": "M 146.1 185 h -24.5 c -7.1 0 -12.9 5.8 -12.9 12.9 v 2.8 c 0 6.4 4.7 11.7 10.9 12.7 v 7.7 c 0 7.1 5.8 12.9 12.9 12.9 h 2.8 c 7.1 0 12.9 -5.8 12.9 -12.9 v -7.7 c 6.1 -1 10.9 -6.3 10.9 -12.7 v -2.8 C 158.9 190.8 153.1 185 146.1 185 z",
        "stroke-width": "2"
      },
      "colour": "#FF1E46"
    },
    {
      "id": "shape_16",
      "tag": "path",
      "attrs": {
        "d": "M 282.6 300.1 c -0.5 0 -1.1 -0.1 -1.5 -0.3 c -1.8 -0.7 -43.1 -18.5 -43.1 -51.1 c 0 -14.8 12 -26.8 26.8 -26.8 c 6.7 0 13 2.4 17.8 6.8 c 4.9 -4.4 11.2 -6.8 17.8 -6.8 c 14.8 0 26.8 12 26.8 26.8 c 0 31.4 -41.3 50.3 -43 51 C 283.7 300 283.1 300.1 282.6 300.1 z",
        "stroke-width": "2"
      },
      "colour": "#FF1E46"
    },
    {
      "id": "shape_17",
      "tag": "path",
      "attrs": {
        "d": "M 300.4 225.9 c 12.6 0 22.8 10.2 22.8 22.8 c 0 29.2 -40.7 47.4 -40.7 47.4 s -40.7 -17.1 -40.7 -47.4 c 0 -12.6 10.2 -22.8 22.8 -22.8 c 7.2 0 13.7 3.4 17.8 8.6 C 286.8 229.3 293.2 225.9 300.4 225.9 M 300.4 217.9 c -6.5 0 -12.7 2 -17.8 5.7 c -5.1 -3.7 -11.3 -5.7 -17.8 -5.7 c -17 0 -30.8 13.8 -30.8 30.8 c 0 35.3 43.7 54 45.6 54.8 c 1 0.4 2 0.6 3.1 0.6 c 1.1 0 2.2 -0.2 3.3 -0.7 c 1.9 -0.8 45.4 -20.8 45.4 -54.7 C 331.2 231.7 317.4 217.9 300.4 217.9 L 300.4 217.9 z",
        "stroke-width": "2"
      },
      "colour": "#6D0F05"
    },
    {
      "id": "shape_18",
      "tag": "polygon",
      "attrs": {
        "points": "290.1 253.5 290.1 243.1 275.1 243.1 275.1 253.5 264.7 253.5 264.7 268.5 275.1 268.5 275.1 278.9 290.1 278.9 290.1 268.5 300.5 268.5 300.5 253.5",
        "stroke-width": "2"
      },
      "colour": "#FFFFFF"
    }
  ]
}

=== DanGrew/homeschooling-app/content/dictionary/entries/duck/colouring.json
{
  "concept": "duck",
  "type": "colouring",
  "viewBox": "0 0 150 150",
  "shapes": [
    {
      "id": "shape_1",
      "tag": "path",
      "attrs": {
        "d": "M69.31,19.83C66.65,15,63.58,6.39,60,5.29c6.17.07,14,3.81,15.56,9,1.91-5.95,7-5.95,10.25-6.17-4.92,4.4-5.25,8.81-5.25,10.8S70.48,22,69.31,19.83Z",
        "stroke-width": "2"
      },
      "colour": "#F1C40F"
    },
    {
      "id": "shape_2",
      "tag": "path",
      "attrs": {
        "d": "M136.24,94.23c0,28.23-35.47,44.1-61.24,44.1s-61.24-15.86-61.24-44.1C13.76,82,22,74,28.35,61,38.11,41,42.27,17.17,75,17.17S111.89,41,121.65,61C128,74,136.24,82,136.24,94.23Z",
        "stroke-width": "2"
      },
      "colour": "#F1C40F"
    },
    {
      "id": "shape_3",
      "tag": "ellipse",
      "attrs": {
        "cx": "52.48",
        "cy": "60.75",
        "rx": "15.94",
        "ry": "10.12",
        "transform": "translate(-16.66 101.53) rotate(-79.71)",
        "stroke-width": "2"
      },
      "colour": "#FFFFFF"
    },
    {
      "id": "shape_4",
      "tag": "ellipse",
      "attrs": {
        "cx": "52.4",
        "cy": "66.69",
        "rx": "6.96",
        "ry": "5.39",
        "transform": "translate(-22.58 106.33) rotate(-79.71)",
        "stroke-width": "2"
      },
      "colour": "#111111"
    },
    {
      "id": "shape_5",
      "tag": "ellipse",
      "attrs": {
        "cx": "97.52",
        "cy": "60.75",
        "rx": "10.12",
        "ry": "15.94",
        "transform": "translate(-9.29 18.4) rotate(-10.29)",
        "stroke-width": "2"
      },
      "colour": "#FFFFFF"
    },
    {
      "id": "shape_6",
      "tag": "ellipse",
      "attrs": {
        "cx": "97.6",
        "cy": "66.69",
        "rx": "5.39",
        "ry": "6.96",
        "transform": "translate(-10.35 18.51) rotate(-10.29)",
        "stroke-width": "2"
      },
      "colour": "#111111"
    },
    {
      "id": "shape_7",
      "tag": "path",
      "attrs": {
        "d": "M118.82,114.66c-8.73,13.53-6.28,29-45.94,29-36.53,0-34.27-15.52-42.32-29-5-8.42-9.87-15.56-5.64-19.27s16.65-.26,25.44-.26,9.92-13.91,22.52-13.91c13.69,0,14.91,13.91,24.45,13.91s22.9-3.54,27.62.26S124.25,106.24,118.82,114.66Z",
        "stroke-width": "2"
      },
      "colour": "#E67E22"
    },
    {
      "id": "shape_8",
      "tag": "path",
      "attrs": {
        "d": "M58.6,105.94c-1.71-3-1.25-5.24.38-6.17s3.8-.19,5.51,2.79,2.31,7.09.68,8S60.31,108.92,58.6,105.94Z",
        "stroke-width": "2",
        "fill": "#000000"
      },
      "noColour": true,
      "fixed": true
    },
    {
      "id": "shape_9",
      "tag": "path",
      "attrs": {
        "d": "M91.4,105.94c1.71-3,1.25-5.24-.38-6.17s-3.8-.19-5.51,2.79-2.31,7.09-.68,8S89.69,108.92,91.4,105.94Z",
        "stroke-width": "2",
        "fill": "#000000"
      },
      "noColour": true,
      "fixed": true
    }
  ]
}
